# Generated by Django 3.1.1 on 2020-10-29 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notifaction_type',
            new_name='notification_type',
        ),
    ]
